### ISSUE TITLE
Main theme file should be called obsidian.css

### ISSUE THREAD

**Issue by THeK3nger** [auroral-ui/aurora-obsidian-md#1]
Hi, the download of the theme fails when I try to download it from the Community Plugins section in Obsidian. I think the problem is that the main theme file should be called `obsidian.css` while the repo calls it `Aurora.css`.

Looking at the inspector I can see that Obsidian is trying to download the file from here: `https://raw.githubusercontent.com/auroral-ui/aurora-obsidian-md/main/obsidian.css`

**Comment by bennyxguo** [comment]
Ah yes, I will change it now, thanks for submitting this issue.

**Comment by bennyxguo** [comment]
This is fixed!~ Thanks for reporting.
