### ISSUE TITLE
Muted == when highlighted

### ISSUE THREAD

**Issue by technicalpickles** [auroral-ui/aurora-obsidian-md#6]
After the realization I made in https://github.com/auroral-ui/aurora-obsidian-md/issues/5 , it seems that for  `==highlighted==` the `==` stick out quite a bit compared to other syntax highlighting like `**bold**`.

I think it'd make sense to use a similar style for `==` that `**` uses

<img width="164" alt="CleanShot 2021-05-20 at 21 37 05@2x" src="https://user-images.githubusercontent.com/159/119069155-954bf600-b9b3-11eb-9995-2137d5872cb1.png">

**Comment by bennyxguo** [comment]
Thanks for reporting, I will look into this one.

**Comment by bennyxguo** [comment]
@technicalpickles This is fixed in the latest commit.
